not compatible with julia 1.7.1
Trying to run this example remotely on GreatLakes is causing an error. Pretty sure it has to do w/the fact I am using julia 1.7.1 because it works fine when running julua 1.6.1.

In a .jl file: 

using Pkg
Pkg.add("ImagePhantoms")
using ImagePhantoms
image = shepp_logan(256)


From the command line: (note that .jl is an alias that points to my julia binary)

[echeek@gl-login2 denoising network]$ jl shep_emis_test.jl  
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`
ERROR: LoadError: UndefVarError: shepp_logan not defined
Stacktrace:
 [1] top-level scope
   @ ~/Differentiable-POGM/denoising network/shep_emis_test.jl:6
in expression starting at /home/echeek/Differentiable-POGM/denoising network/shep_emis_test.jl:6

I wanted to ask here instead of sending this as an email in case there is actually a compatibility issue. The doc says tested w/ julia >= 1.6 but I couldn't find anything else on the web for why this would be happening.